# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='章节')),
                ('name', models.CharField(max_length=32, verbose_name='章节名称')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='课程名称')),
                ('course_img', models.CharField(max_length=64, verbose_name='课程图片')),
                ('level', models.IntegerField(choices=[(1, '初级'), (2, '中级'), (3, '高级')], default=1, verbose_name='难易级别')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.CharField(max_length=255, verbose_name='为什么学习')),
                ('slogon', models.CharField(max_length=255, verbose_name='宣传语')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Course')),
                ('course_recommend', models.ManyToManyField(related_query_name='courserec', to='api.Course')),
            ],
        ),
        migrations.AddField(
            model_name='chapers',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Course', verbose_name='所属课程'),
        ),
    ]
